# -*- coding: utf-8 -*-
"""TraceX-Dfir

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rK4ZvqkY45tJPVNMGEQ6rGsOUWZHXlVn
"""

!pip install flask firebase-admin

COUNTRY_CODES = {
    "+91": "India",
    "+1": "USA / Canada",
    "+44": "United Kingdom",
    "+61": "Australia",
    "+86": "China",
    "+81": "Japan",
    "+49": "Germany",
    "+33": "France",
    "+7": "Russia",
    "+55": "Brazil",
    "+27": "South Africa",
    "+971": "UAE",
    "+966": "Saudi Arabia",
    "+65": "Singapore",
    "+60": "Malaysia",
    "+62": "Indonesia",
    "+92": "Pakistan",
    "+880": "Bangladesh",
    "+94": "Sri Lanka",
    "+977": "Nepal"
}

def detect_country(phone_number):
    for code, country in COUNTRY_CODES.items():
        if phone_number.startswith(code):
            return country
    return "Unknown"

def calculate_risk_score(activity_count):
    if activity_count > 15:
        return 90, "HIGH"
    elif activity_count > 7:
        return 60, "MEDIUM"
    else:
        return 20, "LOW"

from datetime import datetime
import random

def scan_virtual_number(phone_number):
    country = detect_country(phone_number)
    activity_count = random.randint(1, 20)  # simulated behavior
    risk_score, threat_level = calculate_risk_score(activity_count)

    result = {
        "phone_number": phone_number,
        "country": country,
        "provider": "VoIP / Virtual",
        "activity_count": activity_count,
        "risk_score": risk_score,
        "threat_level": threat_level,
        "timestamp": datetime.utcnow().isoformat()
    }
    return result

scan_virtual_number("+919876543210")

def run_fuzzing(protocol):
    test_cases = random.randint(100, 500)
    crashes = random.randint(0, 10)
    vulnerabilities = random.randint(1, 6)

    severity = "HIGH" if crashes > 5 else "MEDIUM" if crashes > 2 else "LOW"

    return {
        "protocol": protocol,
        "total_test_cases": test_cases,
        "crashes_found": crashes,
        "vulnerabilities_detected": vulnerabilities,
        "severity": severity,
        "timestamp": datetime.utcnow().isoformat()
    }

run_fuzzing("Wi-Fi")

def generate_incident_report(number_result, fuzzing_result):
    return {
        "incident_id": f"INC-{random.randint(1000,9999)}",
        "virtual_number_analysis": number_result,
        "fuzzing_analysis": fuzzing_result,
        "status": "INVESTIGATED",
        "generated_at": datetime.utcnow().isoformat()
    }

incident = generate_incident_report(
    scan_virtual_number("+919876543210"),
    run_fuzzing("IoT")
)
incident

from google.colab import files
files.upload()

import firebase_admin
from firebase_admin import credentials, firestore

if not firebase_admin._apps:
    cred = credentials.Certificate(
        "tracex-dfir-firebase-adminsdk-fbsvc-2285a842a1.json"
    )
    firebase_admin.initialize_app(cred)

db = firestore.client()

def save_virtual_number_log(data):
    db.collection("virtual_number_logs").add(data)

result = scan_virtual_number("+919876543210")
save_virtual_number_log(result)
print("Saved virtual number log")

def save_fuzzing_result(data):
    db.collection("fuzzing_results").add(data)

fuzz = run_fuzzing("Wi-Fi")
save_fuzzing_result(fuzz)
print("Saved fuzzing result")

def save_incident_report(data):
    db.collection("incident_reports").add(data)

incident = generate_incident_report(
    scan_virtual_number("+919876543210"),
    run_fuzzing("IoT")
)
save_incident_report(incident)
print("Incident stored successfully")